### ISSUE TITLE
Rerender to see if it works

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/yarp-feedstock#39]
### Additional comment:

@conda-forge-admin please rerender

The failures in https://github.com/conda-forge/yarp-feedstock/pulls seem unrelated to the migration so i'm trying to check.

**Comment by traversaro** [comment]
> The failures in https://github.com/conda-forge/yarp-feedstock/pulls seem unrelated to the migration so i'm trying to check.

Thanks for pointing this out. It is probably a swig 4.2.0 regression. As swig is just used as configuration time to generate bindings, probably we can just pin it to 4.1 .

**Comment by traversaro** [comment]
> > The failures in https://github.com/conda-forge/yarp-feedstock/pulls seem unrelated to the migration so i'm trying to check.
> 
> Thanks for pointing this out. It is probably a swig 4.2.0 regression. As swig is just used as configuration time to generate bindings, probably we can just pin it to 4.1 .

Specific problem tracked in https://github.com/conda-forge/yarp-feedstock/issues/41 .
